"use client";

import { useEffect, useState } from "react";
import Footer from "../../components/Footer";
import Header from "../../components/Header";
import { AddToCalendarButtonType } from "add-to-calendar-button-react";
import { trackGoal } from "fathom-client";
import { AddToCalendarCard } from "../../components/AddToCalendarCard";
import {
  convertIcsToJson,
  generateIssueTitle,
  generateIssueDescription,
  generatedIcsArrayToEvents,
} from "../../utils/utils";
import { useSearchParams } from "next/navigation";
import { useChat } from "ai/react";

type Status = "idle" | "submitting" | "submitted" | "error";

function Output({
  events,
  finished,
  isDev,
  issueStatus,
  lastAssistantMessage,
  lastUserMessage,
  reportIssue,
  setEvents,
  setTrackedAddToCalendarGoal,
  trackedAddToCalendarGoal,
}: {
  events: AddToCalendarButtonType[] | null;
  finished: boolean;
  isDev: boolean;
  issueStatus: Status;
  lastAssistantMessage: string;
  lastUserMessage: string;
  reportIssue: (title: string, description: string) => Promise<void>;
  setEvents: (events: AddToCalendarButtonType[] | null) => void;
  setTrackedAddToCalendarGoal: (trackedAddToCalendarGoal: boolean) => void;
  trackedAddToCalendarGoal: boolean;
}) {
  return (
    <output className="">
      {finished && (
        <>
          <div className="flex justify-center gap-4 flex-wrap">
            {events?.map((props, index) => (
              <AddToCalendarCard
                {...props}
                key={props.name}
                onClick={() => {
                  !trackedAddToCalendarGoal && trackGoal("BQ3VFDBF", 1);
                  setTrackedAddToCalendarGoal(true);
                }}
                setAddToCalendarButtonProps={(props) => {
                  const newArray = [...events];
                  newArray[index] = props;
                  setEvents(newArray);
                }}
              />
            ))}
          </div>
          {issueStatus === "submitting" && (
            <button
              className="bg-red-700 z-50 rounded-xl text-white font-medium px-4 py-2 w-40 fixed bottom-5 right-3"
              disabled
            >
              <span className="loading">
                <span style={{ backgroundColor: "white" }} />
                <span style={{ backgroundColor: "white" }} />
                <span style={{ backgroundColor: "white" }} />
              </span>
            </button>
          )}
          {issueStatus === "idle" && (
            <button
              className="bg-red-700 z-50 rounded-xl text-white font-medium px-4 py-2 hover:bg-red-800 w-40 fixed bottom-5 right-3"
              onClick={() =>
                reportIssue(
                  generateIssueTitle(lastUserMessage),
                  generateIssueDescription(
                    lastUserMessage,
                    lastAssistantMessage,
                    convertIcsToJson(lastAssistantMessage),
                    events
                  )
                )
              }
            >
              Report issue &rarr;
            </button>
          )}
          {issueStatus === "submitted" && (
            <button
              className="bg-red-700 z-50 rounded-xl text-white font-medium px-4 py-2 w-40 fixed bottom-5 right-3"
              disabled
            >
              ✔︎ Reported
            </button>
          )}
          {isDev && (
            <>
              <div className="space-y-8 flex flex-col items-center justify-center max-w-xl mx-auto">
                <div className="bg-white rounded-xl shadow-md p-4 hover:bg-gray-100 transition cursor-pointer border">
                  <p>Prompt</p>
                  <p>{lastUserMessage}</p>
                </div>
              </div>
              <div className="space-y-8 flex flex-col items-center justify-center max-w-xl mx-auto">
                <div
                  className="bg-white rounded-xl shadow-md p-4 hover:bg-gray-100 transition cursor-pointer border"
                  key={lastAssistantMessage}
                >
                  <p>Generated by ChatGPT</p>
                  <code>{lastAssistantMessage}</code>
                </div>
              </div>
              <div className="space-y-8 flex flex-col items-center justify-center max-w-xl mx-auto">
                <div className="bg-white rounded-xl shadow-md p-4 hover:bg-gray-100 transition cursor-pointer border">
                  <p>ICSJson</p>
                  <code>
                    {JSON.stringify(
                      convertIcsToJson(lastAssistantMessage),
                      null,
                      2
                    )}
                  </code>
                </div>
              </div>
              {events?.map((props) => (
                <div
                  className="space-y-8 flex flex-col items-center justify-center max-w-xl mx-auto"
                  key={`code-${props.name}`}
                >
                  <div className="bg-white rounded-xl shadow-md p-4 hover:bg-gray-100 transition cursor-pointer border">
                    <p>AddToCalendarButtonProps</p>
                    <code>{JSON.stringify(props, null, 2)}</code>
                  </div>
                </div>
              ))}
            </>
          )}
        </>
      )}
    </output>
  );
}

export default function Page() {
  const [chatFinished, setChatFinished] = useState(false);
  const [issueStatus, setIssueStatus] = useState<Status>("idle");
  const [events, setEvents] = useState<AddToCalendarButtonType[] | null>(null);
  const [chatEvents, setChatEvents] = useState<
    AddToCalendarButtonType[] | null
  >(null);
  const [trackedAddToCalendarGoal, setTrackedAddToCalendarGoal] =
    useState(false);
  const searchParams = useSearchParams();

  const finished = searchParams.has("message");
  const message = searchParams.get("message") || "";
  const saveIntent = searchParams.get("saveIntent") || "";
  const saveIntentEvent = localStorage.getItem("addToCalendarButtonProps");
  const saveIntentEventJson = JSON.parse(saveIntentEvent || "{}");
  const rawText = searchParams.get("rawText") || "";

  const { append, messages } = useChat({
    onFinish(message) {
      setChatFinished(true);
    },
  });

  useEffect(() => {
    if (rawText) {
      append({ role: "user", content: rawText });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const userMessages = messages.filter((message) => message.role === "user");
  const assistantMessages = messages.filter(
    (message) => message.role === "assistant"
  );

  const lastUserMessage =
    userMessages?.[userMessages.length - 1]?.content || "";
  // const lastAssistantMessage =
  //   assistantMessages?.[userMessages.length - 1]?.content || null;
  const lastAssistantMessage =
    assistantMessages?.[userMessages.length - 1]?.content || "";

  const eventsToUse = saveIntent
    ? [saveIntentEventJson]
    : chatFinished
    ? chatEvents
    : events;

  // set events when changing from not finished to finished
  useEffect(() => {
    if (finished) {
      const events = generatedIcsArrayToEvents(message);
      setEvents(events);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [finished]);

  // set events when changing from not finished to finished
  useEffect(() => {
    if (chatFinished) {
      const events = generatedIcsArrayToEvents(lastAssistantMessage);
      setChatEvents(events);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [chatFinished]);

  const reportIssue = async (title: string, description: string) => {
    setIssueStatus("submitting");
    const response = await fetch("/api/bug", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ title, description }),
    });

    const data = await response.json();

    if (data.issue.success) {
      trackGoal("B2ZT84YS", 0);
      console.log("Successfully created issue:", data.issue);
      setIssueStatus("submitted");
    } else {
      console.log("Error creating issue:", data);
      setIssueStatus("error");
    }
  };

  const isDev = process.env.NODE_ENV === "development";

  return (
    <div className="flex max-w-5xl mx-auto flex-col items-center justify-center py-2 min-h-screen">
      <Header />
      <main className="flex flex-1 w-full flex-col items-center justify-center px-4 mt-12 sm:mt-20">
        <Output
          events={eventsToUse}
          finished={finished || !!saveIntent || chatFinished}
          isDev={isDev}
          issueStatus={issueStatus}
          lastAssistantMessage={chatFinished ? lastAssistantMessage : message}
          lastUserMessage={
            chatFinished ? lastUserMessage : "Generated from message"
          }
          reportIssue={reportIssue}
          setEvents={setEvents}
          setTrackedAddToCalendarGoal={setTrackedAddToCalendarGoal}
          trackedAddToCalendarGoal={trackedAddToCalendarGoal}
        />
      </main>
      <Footer />
    </div>
  );
}
